export const IPC = {
  PRINTER_PRINT:      'printer:print',
  PRINTER_PRINT_ZPL:  'printer:print-zpl',
  PRINTER_PREVIEW:    'printer:preview',
  PRINTER_HISTORY:    'printer:history',
  PRINTER_SCAN:           'printer:scan',
  PRINTER_SET_DEVICE:     'printer:set-device',
  PRINTER_TEST:           'printer:test',
  PRINTER_SET_LABEL_HOME: 'printer:set-label-home',
  SENSOR_UPDATE: 'sensor:update',
  SENSOR_LIST: 'sensor:list',
  WIFI_SAVE: 'wifi:save',
  WIFI_GET: 'wifi:get',
  WIFI_SCAN: 'wifi:scan',
  CONFIG_GET: 'config:get',
  LOGS_TAIL: 'logs:tail',
  REPORT_PRINTS: 'report:prints',
  REPORT_POPULARITY: 'report:popularity',
  REPORT_TEMPS: 'report:temps',
  DEBUG_INFO: 'debug:info',
  DEBUG_SEND_ZPL: 'debug:send-zpl',
  SYSTEM_SET_TIME:          'system:set-time',
  SYSTEM_OPEN_TIME_SETTINGS:'system:open-time-settings',
  SYSTEM_ENABLE_NTP:        'system:enable-ntp',
  UPDATE_CHECK:         'update:check',
  UPDATE_DOWNLOAD:      'update:download',
  UPDATE_PROGRESS:      'update:progress',
  UPDATE_APPLY:         'update:apply',
  UPDATE_GET_SETTINGS:  'update:get-settings',
  UPDATE_SAVE_SETTINGS: 'update:save-settings',
  APP_VERSION:          'app:version',
  APP_QUIT:             'app:quit',
} as const

export type IpcChannel = typeof IPC[keyof typeof IPC]
